name: Trigger auto deployment for desktop

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '"./Dockerfile"/**'
    - '.github/workflows/desktop-AutoDeployTrigger-189020e1-bd5f-4428-8264-0be5e4a03331.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DESKTOP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}"./Dockerfile" 
          registryUrl: desktop8f0858.azurecr.io
          registryUsername: ${{ secrets.DESKTOP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DESKTOP_REGISTRY_PASSWORD }}
          containerAppName: desktop
          resourceGroup: web-app-env
          imageToBuild: desktop8f0858.azurecr.io/desktop:${{ github.sha }}
          
            

     

